# Generated by Django 3.0.5 on 2020-05-04 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_managements', '0002_auto_20200504_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='troupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troupe1', to='event_managements.Troupe'),
        ),
    ]
